defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

repos:
- name: Bridge Foundry
  description: Main repository
  url: https://github.com/bridgefoundry/bridgefoundry.github.io

future: true

excerpt_separator: "<!--more-->"
